language: php

php:
  - 8.1

env:
  - GIT_AUTOCRLF=0
  - GIT_AUTOCRLF=1

# Add checkout with git.autocrlf enabled when GIT_AUTOCRLF=1 so we can verify that that checking out with this enabled
# doesn't cause issues with regexes. See https://github.com/ptlis/diff-parser/issues/7
before_install:
  - |
      if [ "$GIT_AUTOCRLF" -eq "1" ]; then
        cd ../..
        mv $TRAVIS_REPO_SLUG _old
        git config --global core.autocrlf true
        git clone _old $TRAVIS_REPO_SLUG
        cd $TRAVIS_REPO_SLUG
      fi

before_script:
    - composer install

script:
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml
    - ./vendor/bin/phpstan analyze --level=9 src/ tests/
    - ./vendor/bin/phpcs --standard=PSR12 src/ tests/
after_script:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov
