# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

"-": &dockerbuild
  steps:
    - checkout

    - run:
        name: Install System Dependencies
        command: |
          apt update
          apt install -y git libzip-dev zip
          docker-php-ext-install zip

    - run:
        name: Install Composer
        command: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"

    - run:
        name: Install PHP Dependencies
        command: php composer.phar install --no-interaction --prefer-dist

    - run:
        name: Run Unit Tests
        command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml

    - run:
        name: Upload Coverage
        command: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

    - run:
        name: PHPStan
        command: ./vendor/bin/phpstan analyze --level=9 src/ tests/

    - run:
        name: PHPCS
        command: ./vendor/bin/phpcs --standard=PSR12 src/ tests/

jobs:
  php-8_1:
    <<: *dockerbuild
    docker:
      - image: php:8.1

  php-8_2:
    <<: *dockerbuild
    docker:
      - image: php:8.2

workflows:
  version: 2
  php_versions:
    jobs:
      - php-8_1
      - php-8_2